# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'lighthouse-gmaps' do
   
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lighthouse-gmaps
  	pod 'Alamofire', '~> 4.5'
 	pod 'SwiftyJSON'
 	pod 'GoogleMaps', '~> 2.5'
	pod 'GooglePlaces', '~> 2.5'
    pod 'SwiftyBeaver'
  

  target 'lighthouse-gmapsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lighthouse-gmapsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
